services:
  web:
    build: .
    command: sh -c "pipenv run python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.20-alpine3.20
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: