# Generated by Django 4.0.2 on 2022-02-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesubject',
            unique_together={('subject', 'course')},
        ),
    ]
