# Generated by Django 3.2 on 2022-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
