# Generated by Django 3.2 on 2022-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subjectmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectManager',
        ),
    ]
