# Generated by Django 3.2 on 2022-03-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_subjectmanager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursesubject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesubject',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseSubject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
