# Generated by Django 4.0.2 on 2022-02-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizresult_subject_quizresult_subject_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='subject_course',
            new_name='course_subject',
        ),
    ]
