PWA_CONFIG = {
    "name": "College Management System",
    "short_name": "CMS",
    "description": "College management system to manage students performance and library management.",
    "theme_color": "#0A0302",
    "background_color": "#ffffff",
    "display": "standalone",
    "scope": "/",
    "orientation": "portrait-primary",
    "status_bar_color": "default",
    "icons": [ ],
    "icons_apple": [ ],
    "dir": "ltr",
    "lang": "en-US",
    "start_url": "/admin",
}